name = "example_tiny"
description = "Examples for EEPROM_I2C crate"
version = "1.0.0"
licenses = "BSD-3-Clause"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]
tags = ["embedded", "rp2040", "eeprom", "i2c"]
website = "https://github.com/hgrodriguez/eeprom_i2c_examples"

executables = ["example_tiny"]

[gpr-set-externals]
#  I want all dependencies with full debug information
ATOMIC_BUILD_MODE="debug"
BBQUEUE_BUILD_MODE="debug"
CORTEXM_BUILD_MODE="debug"
EDC_CLIENT_BUILD_MODE="debug"
EEPROM_I2C_BUILD_MODE="debug"
ITSYBITSY_RP2040_BSP_BUILD_MODE="debug"
RP2040_HAL_BUILD_MODE="debug"
USB_EMBEDDED_BUILD_MODE="debug"

[[depends-on]]  # Added by alr
gnat_arm_elf = "^12"  # Added by alr

[[depends-on]]  # Added by alr
tiny_rp2040_bsp = "~0.2.1"  # Added by alr

[[depends-on]]  # Added by alr
eeprom_i2c = "^5"  # Added by alr
[[depends-on]]
ltp_305 = "~0.2.0"
